# include Husky-Makefile-Config
include ../huskymak.cfg

SMAPI=smapidjg

CC  =gcc

ifeq ($(DEBUG), 1)
  COPT= -I$(INCDIR) -g
else
  COPT= -I$(INCDIR) -s
endif

all: mpost32.exe

mpost32.exe: mpostp.c
	$(CC) $(COPT) -o mpost32.exe mpostp.c $(LIBDIR)/$(SMAPI).a

clean:
	-del *.obj
	-del *.bak

distclean: clean
	-del *.exe

install: mpost32.exe
	copy mpost32.exe $(BINDIR)

