# include Husky-Makefile-Config
include ../huskymak.cfg

ifeq ($(DEBUG), 1)
  COPT= -I../smapi -I$(INCDIR) -ggdb
else
  COPT= -I../smapi -I$(INCDIR) -s
endif

CDEFS=-D$(OSTYPE) $(ADDCDEFS)

LFLAGS=-L$(LIBDIR) -lsmapi

all: mpost$(EXE)

mpost$(EXE): mpostp.c
	$(CC) $(COPT) $(CDEFS) $(LFLAGS) -o mpost$(EXE) mpostp.c

clean:
	-$(RM) *$(OBJ)
	-$(RM) *~
	-$(RM) core

distclean: clean
	-$(RM) mpost$(EXE)

install: mpost$(EXE)
	$(INSTALL) $(IBOPT) mpost$(EXE) $(BINDIR)

