SMAPI=smapilnx

CC  =gcc
LIBDIR=/usr/local/lib
INCDIR=/usr/local/include
BINDIR=/usr/local/bin
IBOPT=-s

ifeq ($(DEBUG), 1)
  COPT= -I$(INCDIR) -DUNIX -ggdb
else
  COPT= -I$(INCDIR) -DUNIX -s
endif

LOPT= -L$(LIBDIR)

all: mpost

mpost: mpostp.c
	$(CC) $(COPT) $(LOPT) -o mpost mpostp.c -l$(SMAPI)

clean:
	-rm *.o *~ core

distclean: clean
	-rm mpost

install: mpost
	install $(IBOPT) mpost $(BINDIR)

