
SMAPIDIR=../smapi
SMAPI=smapirxw
TARGET=mpostnt.exe

CC=gcc -D__NT__ -Zwin32 -Zsys

default: $(TARGET)

clean:
	-rm mpostp.o

distclean: clean
	-rm $(TARGET)

$(TARGET): mpostp.c
	$(CC) -I.. -I$(SMAPIDIR) -o $(TARGET) mpostp.c -L$(SMAPIDIR) -l$(SMAPI)
