# $Id$
# Microsoft Visual C++ Makefile

CC     =cl
CFLAGS =-nologo -Zp1 -I..
CDEFS  =-D__NT__ -D_CONSOLE
COPT   =-O2
LOPT   =/link /opt:nowin98
LIBS   = ..\smapi\smapimvc.lib User32.lib

all: mpost.exe

mpost.exe: mpostp.c 
        $(CC) $(CFLAGS) $(CDEFS) $(COPT) -Fempost mpostp.c $(LIBS) $(LOPT)

clean:
	-del *.obj

distclean: clean
	-del *.exe
